#Main
LAST_CHANNEL = 14
TONE_DETECT_REC_LENGTH = 50  # ms, at least 50. Length of recording to be analyzed during scanning before proceeding to next channel. Actual time spent on channel will be longer.
CANCEL_HELP_TIMEOUT = 8  # seconds. Currently not used since cancellation by caller was removed. May be deleted soon.
TESTING_STAR_DETECT_TIMEOUT = 15 # seconds. Time to enter "*" after being prompted for the operator code during the testing procedure.
OPERATOR_ID_TIMEOUT = 10 # seconds. Time to enter pound followed by the 3-digit operator code after entering "*". Applies during testing and alert procedures.
TRANSMIT_DELAY = 1.5  # seconds. Delay after activating PTT and before playing files.
DISABLE_ERROR_BROADCASTING = false  # ARMS will normally announce a configuration errors on the alert channel if there is sufficient valid configuration to do so.

#Loop lengths
INITIAL_ALERT_SHORT_DELAY_LENGTH = 7  # seconds
INITIAL_ALERT_NUM_SHORT_DELAYS = 2
INITIAL_ALERT_LONG_DELAY_LENGTH = 120  # seconds
SHORT_DELAY_MESSAGE_LOOP_LENGTH = 60  # seconds
MODERATE_DELAY_MESSAGE_LOOP_LENGTH = 120  # seconds
LONG_DELAY_MESSAGE_LOOP_LENGTH = 120  # seconds
IC_DEFINED_MESSAGE_LOOP_LENGTH = 120  # seconds

#hamlib
RIGCTLD_ADDRESS = "127.0.0.1"
RIGCTLD_PORT = 4532
SWITCH_TO_MEM_MODE = true
DISABLE_PTT = false
RIGCTLD_OPERATION_TIMEOUT = 7  # seconds

#Long tone detection. (Long tone zero invokes the alert procedure; long tone hash invoked the testing procedure.)
LONG_TONE_SAMPLING_PERIOD = 100  # ms, at least 100.
LONG_TONE_TOTAL_SAMPLES = 50  # number of samples
LONG_TONE_REQUIRED_POSITIVE_SAMPLES = 20  # number of positive samples to conclude LPZ
LONG_TONE_MAX_POSITIVE_SAMPLES = 250  # the number of samples that must be exceeded to conclude a false positive. Set higher than LPZ_TOTAL_SAMPLES to disable false positives.

#Silence detection (before transmitting and before starting CANCEL_HELP_TIMEOUT)
DCD_SAMPLING_PERIOD = 200  # ms
DCD_REQ_CONSEC_ZEROES = 6 # number of consecutive DCD = 0 samples to conclude silence

#Audio
#Comment out either line to use default device (not recommended)
OUTPUT_AUDIO_DEVICE_SUBSTRING = "USB"
INPUT_AUDIO_DEVICE_SUBSTRING = "USB"

#Debugging
DEBUG_MODE = true
DEBUG_OUTPUT_AUDIO_DEVICE_SUBSTRING = "pulse"
DEBUG_INPUT_ADUIO_DEVICE_SUBSTRING = "pulse"
USING_HAMLIB_DUMMY = true

[PARAGRAPHS]
# File paths are taken relative to the audio directory. For example, "call_sign.wav" corresponds to "audio/call_sign.wav".
ADVISE_CALLER_HEARD = ["beep.wav", "system_is_calling_help.wav", "call_sign.wav"]
INITIAL_ALERT = ["ascending_beep.wav", "call_sign.wav", "lpz_detected.wav"]
IC_DEFINED = ["all_stations_standby.wav"]
SHORT_DELAY = ["1_minute_delay.wav", "remain_on_frequency.wav"]
MODERATE_DELAY = ["10_minute_delay.wav", "remain_on_frequency.wav"]
LONG_DELAY = ["20_minute_delay.wav", "remain_on_frequency.wav"]
ALERT_CANCELLED = ["alert_handled.wav"]
ARMS_RETURNING_NORMAL_OP = ["ARMS_returning_normal_op.wav", "call_sign.wav"]
ENTER_OPERATOR_CODE = ["enter_operator_code.wav"]
IC_CODE_INVALID = ["ic_code_invalid.wav"]
IC_CODE_TIMED_OUT = ["ic_code_timed_out.wav"]
TESTING = ["testing.wav", "call_sign.wav"]
TESTING_CODE_INVALID = ["testing_code_invalid.wav"]
TESTING_CODE_TIMED_OUT = ["testing_code_timed_out.wav"]

[OPERATORS]
016 = true  # K7AA
038 = true  # AF7YX
050 = true  # W7RJA
072 = true  # KJ7PUX
094 = false

216 = false
238 = false
250 = false
272 = false
294 = false

416 = false
438 = false
450 = false
472 = false
494 = false

616 = false
638 = false
650 = false
672 = false
694 = false

816 = false
838 = false
850 = false
872 = false
894 = false